INSERT INTO APP_USER(ID, FIRST_NAME, LAST_NAME) VALUES (10001, 'Ali', 'Madani');
INSERT INTO APP_USER(ID, FIRST_NAME, LAST_NAME) VALUES (10002, 'Mahsa', 'Javar');
INSERT INTO APP_USER(ID, FIRST_NAME, LAST_NAME) VALUES (10003, 'Salman', 'Ahvazi');


